services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - 8000:8000

  client01:
    build: 
      context: ./client
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app # docker-compose.ymlのディレクトリをコンテナの/appにマウントさせる
    depends_on:
      - server
    ports:
      - 3000:3000

  client02:
    build: 
      context: ./client
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app # docker-compose.ymlのディレクトリをコンテナの/appにマウントさせる
    depends_on:
      - server
    ports:
      - 3001:3000